(function() {
  var T = {
    'w':      ['w                  Move forward to start of next word.',
               '',
               'A word is a sequence of letters, digits, and underscores,',
               'or a sequence of other non-blank characters, separated by',
               'whitespace.  See also |W| for WORD motions.'],
    'b':      ['b                  Move backward to start of previous word.'],
    'e':      ['e                  Move forward to end of current/next word.'],
    'W':      ['W                  Like w, but a WORD is any non-blank characters.'],
    'B':      ['B                  Like b, but for WORDs.'],
    'E':      ['E                  Like e, but for WORDs.'],
    'h':      ['h                  Move cursor left.'],
    'j':      ['j                  Move cursor down.'],
    'k':      ['k                  Move cursor up.'],
    'l':      ['l                  Move cursor right.'],
    'x':      ['x                  Delete character under cursor. Also |dl|.'],
    'dd':     ['dd                 Delete [count] lines. Yanks to register.'],
    'dw':     ['dw                 Delete from cursor to start of next word.'],
    'd':      ['d{motion}          Delete text that {motion} moves over.',
               '',
               'Examples:  dw   d$   dG   dgg   d%   dfe'],
    'D':      ['D                  Delete to end of line. Same as d$.'],
    'c':      ['c{motion}          Change text that {motion} moves over.',
               '                   Deletes and enters insert mode.',
               '',
               'Special: cw/cW behave like ce/cE (vim convention).'],
    'cc':     ['cc                 Change whole line.'],
    'C':      ['C                  Change to end of line. Same as c$.'],
    'y':      ['y{motion}          Yank (copy) text that {motion} moves over.',
               '                   Also copies to system clipboard.'],
    'yy':     ['yy                 Yank whole line. Also copies to clipboard.'],
    'p':      ['p                  Put (paste) after cursor / below line.',
               '                   Pastes linewise if yanked with yy/dd.'],
    'P':      ['P                  Put (paste) before cursor / above line.'],
    'i':      ['i                  Enter insert mode before cursor.'],
    'I':      ['I                  Enter insert mode at first non-blank.'],
    'a':      ['a                  Enter insert mode after cursor.'],
    'A':      ['A                  Enter insert mode at end of line.'],
    'o':      ['o                  Open new line below, enter insert mode.'],
    'O':      ['O                  Open new line above, enter insert mode.'],
    'r':      ['r{char}            Replace character under cursor with {char}.'],
    'R':      ['R                  Enter replace mode (overtype).'],
    'u':      ['u                  Undo last change.'],
    'U':      ['U                  Undo all changes on current line.',
               '                   Restores the line to its state when the',
               '                   cursor first moved to it.'],
    'gg':     ['gg                 Go to first line of buffer.'],
    'G':      ['G                  Go to last line. {count}G goes to line {count}.'],
    'n':      ['n                  Repeat last search in same direction.'],
    'N':      ['N                  Repeat last search in opposite direction.'],
    '/':      ['/pattern           Search forward for pattern.',
               '                   Use \\c for case-insensitive: /foo\\c'],
    '?':      ['?pattern           Search backward for pattern.'],
    '*':      ['*                  Search forward for word under cursor.'],
    '#':      ['#                  Search backward for word under cursor.'],
    '%':      ['%                  Jump to matching bracket: ( ) [ ] { }'],
    'v':      ['v                  Start character-wise visual selection.'],
    'V':      ['V                  Start line-wise visual selection.'],
    'f':      ['f{char}            Find {char} forward on current line.'],
    'F':      ['F{char}            Find {char} backward on current line.'],
    't':      ['t{char}            Move to just before {char} forward.'],
    'T':      ['T{char}            Move to just after {char} backward.'],
    ';':      [';                  Repeat last f/F/t/T search.'],
    ',':      [',                  Repeat last f/F/t/T in opposite direction.'],
    '.':      ['.                  Repeat last change.'],
    '~':      ['~                  Toggle case of character under cursor.'],
    'J':      ['J                  Join current line with next (add space).'],
    'gJ':     ['gJ                 Join current line with next (no space).'],
    'gx':     ['gx                 Open URL under cursor in browser.'],
    'zz':     ['zz                 Scroll to center cursor line on screen.'],
    'zt':     ['zt                 Scroll cursor line to top of screen.'],
    'zb':     ['zb                 Scroll cursor line to bottom of screen.'],
    ':s':     [':s/old/new/        Substitute first "old" with "new" on line.',
               ':s/old/new/g       Substitute all on current line.',
               ':%s/old/new/g      Substitute all in entire file.',
               ':#,#s/old/new/g    Substitute in line range (e.g. :3,7s/...).',
               ':%s/old/new/gc     Substitute with confirmation (y/n/a/q).'],
    ':w':     [':w                 Save (download as file).',
               ':w name            Save as name.',
               ':wq                Save and quit.'],
    ':q':     [':q                 Quit (back to previous page).',
               ':q!                Quit (hacker exit with style).',
               ':qa                Quit all.'],
    ':e':     [':e file            Open new buffer with filename.',
               ':enew              New empty buffer.',
               ':Ex                Browse available files (see :help :Ex).'],
    ':r':     [':r filename        Read file and insert below cursor.',
               '',
               'Blog post shortnames:',
               '  :r emergent-religion',
               '  :r terminal-velocity',
               '  :r friction-economy',
               '  :r knowledge-sidecar',
               '  :r claude-code-setups',
               '  :r trust-your-engineers',
               '  :r calmhive',
               '  :r dadbod-grip',
               '  :r pig-security-wisdom',
               '  :r natural-language-first',
               '  :r ai-engineer-spec',
               '  :r spiritual-bliss',
               '  :r ai-dev-tooling'],
    ':set':   [':set OPTION         Set an option. :set noOPTION to unset.',
               '',
               'Display:',
               '  :set nu            Line numbers in the gutter.',
               '  :set nonu          Hide line numbers.',
               '  :set rnu           Relative line numbers (distance from cursor).',
               '  :set nornu         Disable relative numbers.',
               '  :set cul           Highlight the cursor line with a subtle background.',
               '  :set nocul         Disable cursor line highlight.',
               '  :set list          Show invisible characters (tabs, spaces, EOL).',
               '  :set nolist        Hide invisible characters.',
               '  :set wrap          Wrap long lines to fit the screen.',
               '  :set nowrap        Disable word wrap (horizontal scroll).',
               '',
               'Search:',
               '  :set ic            Ignore case when searching (/foo matches FOO).',
               '  :set noic          Exact case matching (default).',
               '  :set scs           Smart case: case-sensitive only when pattern',
               '                     contains uppercase. Requires :set ic.',
               '  :set noscs         Disable smart case.',
               '  :set hls           Highlight all search matches in the buffer.',
               '  :set nohls         Disable search highlighting.',
               '  :set is            Incremental search: jump to matches as you type.',
               '  :set nois          Disable incremental search.',
               '',
               'See also :nohlsearch to clear current highlights without',
               'changing the setting. Use \\c in a pattern for one-off',
               'case-insensitive search: /foo\\c'],
    ':nohlsearch': [':nohlsearch   Clear search highlighting. Also :noh, :nohl.'],
    'Ctrl-r': ['CTRL-R             Redo (undo the undo).'],
    'Ctrl-g': ['CTRL-G             Show file name, line count, and position.'],
    'Ctrl-o': ['CTRL-O             Go to older position in jump list.',
               '                   Auto-recorded when cursor moves 2+ lines.'],
    'Ctrl-i': ['CTRL-I             Go to newer position in jump list.'],
    'Ctrl-f': ['CTRL-F             Page down (forward).'],
    'Ctrl-b': ['CTRL-B             Page up (backward).'],
    'Ctrl-d': ['CTRL-D             Half page down.'],
    'Ctrl-u': ['CTRL-U             Half page up.'],
    'Ctrl-a': ['CTRL-A             Increment number under cursor.'],
    'Ctrl-x': ['CTRL-X             Decrement number under cursor.'],
    ':Ex':    [':Ex                Browse available blog posts (netrw-style).',
               ':Explore           Same as :Ex.',
               ':Sexplore          Same as :Ex (no split in this editor).',
               ':Vexplore          Same as :Ex (no split in this editor).',
               '',
               'Navigate with j/k, press Enter to open a post.',
               'Press - from any buffer to return to the explorer.'],
    ':color': [':colorscheme name  Change colorscheme. Tab to preview.',
               '                   32 schemes available.'],
    ':zen':   [':zen               Toggle zen (distraction-free) mode.'],
    ':tutor': [':tutor             Open the interactive Vim tutorial.',
               '                   Full vimtutor with practice exercises.'],
    ':help':  [':help              Show general help.',
               ':help {topic}      Show help for a specific topic.',
               '',
               'Topics: w b e d c y p u U gg G n N / ? * # % v V',
               '        f t r R o O i a . ~ J m q @ :s :w :q :e :r',
               '        :set :marks :! Ctrl-r Ctrl-g Ctrl-o Ctrl-i',
               '        Ctrl-f Ctrl-b Ctrl-d Ctrl-u Ctrl-a Ctrl-x',
               '        :color :zen :tutor :Ex :nohlsearch',
               '        text-objects macros marks insert-index user-manual'],
    'insert-index': ['Insert mode commands:',
                     '',
                     '  Any character    Insert at cursor position.',
                     '  Backspace        Delete character before cursor.',
                     '  Escape           Return to normal mode.',
                     '  Cmd+V            Paste from system clipboard.'],
    'user-manual': ['jorypestorious.com/vim',
                    '',
                    'This is a browser-based vim editor. It supports the core',
                    'vim command set: motions, operators, visual mode, search,',
                    'substitution, undo/redo, registers, and more.',
                    '',
                    'Type :help for the full command reference.',
                    'Type :tutor for an interactive tutorial.',
                    '',
                    'All commands from vimtutor lessons 1-7 are supported:',
                    '  Lesson 1: h j k l, x, i, A, :wq, :q!',
                    '  Lesson 2: dw, d$, de, dd, 2w, d2w, 0, u, U, Ctrl-R',
                    '  Lesson 3: p, r, ce, c$, cc',
                    '  Lesson 4: Ctrl-G, G, gg, /, ?, n, N, Ctrl-O, Ctrl-I, %, :s',
                    '  Lesson 5: :!, :w, :r, v+:w',
                    '  Lesson 6: o, O, a, e, R, y, yw, yy, :set ic/hls/is',
                    '  Lesson 7: :help, :e, Tab completion']
  };

  T['CTRL-R'] = T['Ctrl-r'];
  T['CTRL-G'] = T['Ctrl-g'];
  T['CTRL-O'] = T['Ctrl-o'];
  T['CTRL-I'] = T['Ctrl-i'];
  T['CTRL-F'] = T['Ctrl-f'];
  T['CTRL-B'] = T['Ctrl-b'];
  T['CTRL-D'] = T['Ctrl-d'];
  T['CTRL-U'] = T['Ctrl-u'];
  T['CTRL-A'] = T['Ctrl-a'];
  T['CTRL-X'] = T['Ctrl-x'];
  T['c_CTRL-D'] = ['CTRL-D in command mode: Tab cycles completions.'];
  T['nohlsearch'] = T[':nohlsearch'];
  T['set'] = T[':set'];
  T['options'] = T[':set'];
  T['m'] = ['m{a-z}          Set mark at current cursor position.',
            '`{a-z}          Jump to exact mark position (row and column).',
            "'{a-z}          Jump to first non-blank character of marked line.",
            ':marks          List all set marks with line content preview.'];
  T['marks'] = T['m'];
  T[':marks'] = T['m'];
  T['q'] = ['q{a-z}          Start recording macro into register {a-z}.',
            'q               Stop recording.',
            '@{a-z}          Execute the macro stored in register {a-z}.',
            '@@              Repeat the most recently played macro.',
            '{count}@{a-z}   Execute macro N times.',
            '',
            'Safety limits: 10 recursion depth, 1000 keystrokes per replay.'];
  T['macros'] = T['q'];
  T['@'] = T['q'];
  T['text-objects'] = ['Text objects select regions of text for operators.',
                       '',
                       'WORDS AND PARAGRAPHS',
                       '  iw aw    inner / a word',
                       '  iW aW    inner / a WORD (non-whitespace)',
                       '  ip ap    inner / a paragraph',
                       '',
                       'PAIRED DELIMITERS',
                       '  i( a(    inner / a parentheses   (alias: ib ab)',
                       '  i[ a[    inner / a square brackets',
                       '  i{ a{    inner / a curly braces  (alias: iB aB)',
                       '  i< a<    inner / a angle brackets',
                       '  i" a"    inner / a double-quoted string',
                       "  i' a'    inner / a single-quoted string",
                       '  i` a`    inner / a backtick string',
                       '',
                       'i selects the content between delimiters (exclusive).',
                       'a selects the content PLUS the delimiters (inclusive).',
                       'Brackets match across lines using the same algorithm as %.',
                       'Quotes are line-local; no nesting.',
                       '',
                       'Compose with any operator: ci(, da", yi{, >ip, gUiw',
                       'Also works in visual mode: vi(, va"'];
  var TO = ['i(','a(','i)','a)','i[','a[','i]','a]','i{','a{','i}','a}','i<','a<','i"','a"',"i'","a'",'i`','a`','ib','ab','iB','aB'];
  for (var ti = 0; ti < TO.length; ti++) T[TO[ti]] = T['text-objects'];

  T['i_CTRL-H'] = ['CTRL-H in insert mode: same as Backspace.',
                   'Deletes the character before the cursor, or joins with the',
                   'previous line if at column 0.'];
  T['i_CTRL-W'] = ['CTRL-W in insert mode: delete the word before the cursor.',
                   '',
                   'Walks backward past whitespace, then past the run of word or',
                   'non-word characters, and removes that span. Fast for backing',
                   'out of a just-typed token without leaving insert mode.'];
  T['i_CTRL-U'] = ['CTRL-U in insert mode: delete from column 0 to the cursor.',
                   '',
                   'Equivalent to pressing Home, then Shift+End Delete in a',
                   'regular text field. Useful for discarding a whole line of',
                   'typed text without leaving insert.'];
  T['i_CTRL-O'] = ['CTRL-O in insert mode: run one normal-mode command, then',
                   'return to insert mode automatically.',
                   '',
                   'Example: while typing, press CTRL-O then dw to delete the',
                   'next word and continue typing. Counts and multi-key commands',
                   'work: CTRL-O 5j moves five lines, CTRL-O dd deletes a line.',
                   'Press Escape during the pending state to stay in normal mode.'];

  T['Ctrl-v'] = ['CTRL-V             Enter block (rectangular) visual mode.',
                 '',
                 'Selection is a rectangle bounded by cursor and anchor on',
                 'each axis independently. Operators apply column-wise.',
                 '',
                 'In block visual mode:',
                 '  d / x     delete the rectangle, shift remainder left',
                 '  c         delete the rectangle, then enter insert',
                 '  y         yank the rectangle',
                 '  I         prepend typed text to every row (Escape replays)',
                 '  A         append typed text to every row (Escape replays)',
                 '  v V       convert to char / line visual',
                 '  CTRL-V    exit back to normal mode',
                 '  o         swap anchor and cursor'];
  T['CTRL-V'] = T['Ctrl-v'];
  T['v_CTRL-V'] = T['Ctrl-v'];

  T['gv'] = ['gv             Reselect the last visual range.',
             '',
             'Works for char, line, and block visual modes. The previous',
             'range is remembered across normal-mode commands, so you can',
             'operate on a region, look at the result, then gv to reselect',
             'and try a different operator.'];

  T['v_o'] = ['o (in visual mode): swap the anchor and the cursor.',
              '',
              'Lets you extend either end of the selection. Press o to move',
              'the cursor to the other end; cursor motions then grow or',
              'shrink the selection from that end instead.'];

  T[':g'] = [':g/pat/cmd      Run cmd on every line matching pat.',
             ':v/pat/cmd      Run cmd on every line NOT matching pat.',
             '',
             'Supported subcommands:',
             '  :g/pat/d              delete matching lines',
             '  :v/pat/d              delete non-matching lines',
             '  :g/pat/s/from/to/g    substitute only in matching lines',
             '  :g/pat/s/from/to/     single substitution per matching line',
             '',
             'Example: remove all TODO lines:   :g/TODO/d',
             'Example: uppercase FIX tokens:    :g/FIX/s/fix/FIX/g'];
  T[':v'] = T[':g'];
  T['g'] = T[':g'];

  T[':sort'] = [':sort           Sort the whole buffer lexicographically.',
                ':%sort          Same as :sort.',
                ":'<,'>sort      Sort the last visual selection.",
                ':N,Msort        Sort lines N through M (1-indexed).',
                ':sort u         Sort and remove duplicate adjacent lines.',
                '',
                'Sort is stable. Empty buffer is a no-op.'];
  T['sort'] = T[':sort'];

  T['search-anchors'] = ['Word-boundary and magic-mode anchors for search.',
                         '',
                         '  \\<word     matches word only when it starts a word',
                         '  word\\>     matches word only when it ends a word',
                         '  \\<word\\>   whole-word match',
                         '',
                         'Example: /\\<foo\\> matches foo but not food or foobar.',
                         '',
                         'Case modifiers (place anywhere in the pattern):',
                         '  \\c        force case-insensitive',
                         '  \\C        force case-sensitive',
                         '',
                         'Works with /, ?, :s, :g, and :v.'];
  T['\\<'] = T['search-anchors'];
  T['\\>'] = T['search-anchors'];
  T['\\c'] = T['search-anchors'];
  T['\\C'] = T['search-anchors'];

  T['expandtab'] = [':set expandtab        Tab inserts spaces instead of a tab.',
                    ':set noexpandtab      Tab inserts a real tab character.',
                    '',
                    'Aliases: :set et / :set noet',
                    '',
                    'Pairs with :set tabstop=N to control how many spaces are',
                    'inserted per Tab.'];
  T['noexpandtab'] = T['expandtab'];
  T['et'] = T['expandtab'];
  T['tabstop'] = [':set tabstop=N        Width of a tab in columns. Default 4.',
                  '',
                  'Alias: :set ts=N',
                  '',
                  'When :set expandtab is on, Tab inserts N spaces.',
                  'When off, Tab inserts a literal tab character.'];
  T['ts'] = T['tabstop'];
  T['shiftwidth'] = [':set shiftwidth=N     Columns per > or < step. Default 4.',
                     '',
                     'Alias: :set sw=N',
                     '',
                     'Controls the indent depth of the > and < operators.'];
  T['sw'] = T['shiftwidth'];
  T['autoindent'] = [':set autoindent       Copy the previous line\'s indent on Enter.',
                     ':set noautoindent     New lines start at column 0.',
                     '',
                     'Aliases: :set ai / :set noai'];
  T['ai'] = T['autoindent'];

  T[':!'] = [':!{cmd}         Run a shell command.',
             '',
             'Available commands:',
             '  :!ls           Directory listing',
             '  :!ls blog/     Blog post listing',
             '  :!cat slug     Print blog post content',
             '  :!pwd          Print working directory',
             '  :!whoami       Print current user',
             '  :!date         Print current date',
             '  :!echo text    Echo text',
             '  :!fortune      Random programming fortune',
             '  :!cowsay text  Cowsay',
             '',
             'Press u to return to your buffer after shell output.'];

  window.VIM_HELP_TOPICS = T;

  window.VIM_HELP_MAIN = function(VIM_VERSION) {
    return [
      'jorypestorious.com/vim v' + VIM_VERSION + '                          *help*',
      '',
      'MOVEMENT',
      '  h j k l     left, down, up, right',
      '  w b e       word forward / backward / end',
      '  W B E       WORD forward / backward / end',
      '  ge gE       end of previous word / WORD',
      '  0 $ ^       line start / end / first non-blank',
      '  gg G        buffer start / end',
      '  H M L       screen top / middle / bottom',
      '  { }         paragraph backward / forward',
      '  %           matching bracket',
      '  f{c} F{c}   find char forward / backward',
      '  t{c} T{c}   till char forward / backward',
      '  ; ,         repeat / reverse last find',
      '  gx          open URL under cursor',
      '  Ctrl-o      jump list older    Ctrl-i  newer',
      '',
      'OPERATORS + MOTIONS',
      '  d{motion}   delete (dw, d$, dG, d%...)',
      '  c{motion}   change (cw, c$, cG...)',
      '  y{motion}   yank (yw, y$, yG...)',
      '  >{motion}   indent     >>{count}  indent lines',
      '  <{motion}   dedent     <<{count}  dedent lines',
      '  g~{motion}  toggle case',
      '  gu{motion}  lowercase    gU{motion}  uppercase',
      '  {count}{motion}  repeat motion (3w, 5j, 2dd...)',
      '',
      'INSERT MODE',
      '  i I         insert before cursor / at first non-blank',
      '  a A         insert after cursor / at end of line',
      '  o O         open line below / above',
      '  s S         substitute char / line',
      '  C           change to end of line',
      '  R           replace mode (overwrite characters)',
      '  Ctrl-h      delete character before cursor (like Backspace)',
      '  Ctrl-w      delete the word before the cursor',
      '  Ctrl-u      delete from column 0 to the cursor',
      '  Ctrl-o      run ONE normal-mode command, then return to insert',
      '  Cmd+V       paste from system clipboard',
      '  Esc         return to normal mode',
      '',
      'EDITING',
      '  x           delete character',
      '  r{c}        replace character with {c}',
      '  ~           toggle case',
      '  dd          delete line (also yanks)',
      '  D           delete to end of line',
      '  yy          yank (copy) line (also copies to clipboard)',
      '  p           paste below / after',
      '  P           paste above / before',
      '  J           join lines       gJ   join without space',
      '  .           repeat last change',
      '  &           repeat last substitution',
      '  u           undo             U    undo all on line',
      '  Ctrl-r      redo',
      '  Ctrl-a      increment number',
      '  Ctrl-x      decrement number',
      '',
      'SCROLLING',
      '  Ctrl-f      page down         Ctrl-b  page up',
      '  Ctrl-d      half page down    Ctrl-u  half page up',
      '  zz          center cursor on screen',
      '  zt          cursor to top     zb      cursor to bottom',
      '',
      'TEXT OBJECTS',
      '  iw aw       inner / around word          iW aW   WORD',
      '  ip ap       inner / around paragraph',
      '  i( a(       inner / around parens        (alias: ib ab)',
      '  i[ a[       inner / around square brackets',
      '  i{ a{       inner / around curly braces  (alias: iB aB)',
      '  i< a<       inner / around angle brackets',
      '  i" a"       inner / around double-quoted string',
      "  i' a'       inner / around single-quoted string",
      '  i` a`       inner / around backtick string',
      '  Works with d, c, y, >, <, g~, gu, gU and visual mode',
      '',
      'MARKS',
      '  m{a-z}      set mark',
      '  `{a-z}      jump to exact mark position',
      "  '{a-z}      jump to first non-blank of marked line",
      '  :marks      list all marks',
      '',
      'MACROS',
      '  q{a-z}      record macro into register',
      '  q           stop recording',
      '  @{a-z}      play macro     @@  repeat last macro',
      '  {count}@a   play macro N times',
      '',
      'VISUAL MODE',
      '  v           character-wise     V       line-wise',
      '  Ctrl-v      block (rectangular) visual',
      '  gv          reselect the last visual range',
      '  o           swap the anchor and the cursor',
      '  d / x       delete selection',
      '  c           change selection',
      '  y           yank selection',
      '  ~ U u       toggle / upper / lower case',
      '  > <         indent / dedent',
      '  In block visual, I prepends and A appends to every row in the rectangle.',
      '',
      'SEARCH',
      '  /pattern    search forward     ?pattern  search backward',
      '  n N         next / previous match',
      '  * #         word under cursor forward / backward',
      '  \\<word\\>    whole-word match (word boundary anchors)',
      '  \\c \\C       force case-insensitive / case-sensitive',
      '  Ctrl-g      file info (name, lines, position)',
      '',
      'SUBSTITUTE AND FILTER',
      '  :s/old/new/        first on current line',
      '  :s/old/new/g       all on current line',
      '  :%s/old/new/g      all in file',
      '  :#,#s/old/new/g    in line range',
      '  :%s/old/new/gc     with confirmation (y/n/a/q)',
      '  :g/pat/d           delete every line matching pat',
      '  :v/pat/d           delete every line NOT matching pat',
      '  :g/pat/s/a/b/g     substitute only within matching lines',
      '  :sort              sort buffer lexicographically   :sort u  unique',
      "  :'<,'>sort         sort the last visual selection",
      '  :nohlsearch        clear search highlighting',
      '',
      'COMMANDS',
      '  :w          save (download)    :w name   save as',
      '  :e slug     open blog post (Tab completes slugs)',
      '  :enew       empty buffer',
      '  :r slug     read blog post below cursor',
      '  :q          quit               :q!       quit with style',
      '  :wq         save and quit',
      '  :!ls        directory listing   :!ls blog/  blog posts',
      '  :!cat slug  print blog post     :!pwd  :!whoami  :!date',
      '  :set nu     line numbers       :set nonu   (or :unset nu)',
      '  :set rnu    relative numbers   :set nornu  (or :unset rnu)',
      '  :set ic     ignore case        :set noic   (or :unset ic)',
      '  :set scs    smart case         :set noscs  (or :unset scs)',
      '  :set hls    highlight search   :set nohls  (or :unset hls)',
      '  :set is     incremental search :set nois   (or :unset is)',
      '  :set cul    cursor line        :set nocul  (or :unset cul)',
      '  :set list   show whitespace    :set nolist (or :unset list)',
      '  :set wrap   word wrap          :set nowrap (or :unset wrap)',
      '  :set et     expand tabs        :set noet   (or :unset et)',
      '  :set ts=N   tab width          :set sw=N   indent step',
      '  :set ai     auto indent        :set noai   (or :unset ai)',
      '  :nohlsearch clear highlights',
      '  :intro      return to dashboard',
      '  :zen        toggle zen mode',
      '  :color name 32 colorschemes (Tab to preview)',
      '  :tutor      interactive vim tutorial',
      '  :help topic help on any command (e.g. :help w, :help :s)',
      '',
      'Yank copies to system clipboard. Cmd+V pastes.',
      'Tab / Shift+Tab cycle completions in command mode.',
      'Preferences saved to localStorage.',
      '',
      'New to vim? Type :tutor to learn the basics.',
      '',
      'Press u to return to your buffer.'
    ];
  };
})();
